coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/etc/trino/security/trino.p12
http-server.https.keystore.key=${ENV:TRINO_TLS_KEYSTORE_PASSWORD}
http-server.authentication.type=PASSWORD
internal-communication.shared-secret=${ENV:TRINO_INTERNAL_SHARED_SECRET}
discovery.uri=http://trino-secure-coordinator:8080
catalog.management=static
sql.forced-session-time-zone=UTC
retry-policy=NONE
query.remote-task.max-error-duration=15s
openmetrics.jmx-object-names=trino.execution:name=QueryManager
