coordinator=false
http-server.http.port=8080
internal-communication.shared-secret=${ENV:TRINO_INTERNAL_SHARED_SECRET}
discovery.uri=http://trino-secure-coordinator:8080
catalog.management=static
sql.forced-session-time-zone=UTC
retry-policy=NONE
query.remote-task.max-error-duration=15s
shutdown.grace-period=5s
