coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
discovery.uri=http://trino-coordinator:8080
catalog.management=static
sql.forced-session-time-zone=UTC
openmetrics.jmx-object-names=trino.execution:name=QueryManager
